name: build_web
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build web app

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: "3.13.3"
            channel: "stable"
            cache: true
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run flutter dependencies.
        run: flutter pub get
      - name: run flutter build
        run: flutter build web
      - name: run deploy web
        run: |
          cd build/web
          git init
          git config --global user.email zxlin1893@gmail.com
          git config --global user.name zxlin1893
          git status
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/zxlin1893/test_flutter_actions.git
          git branch -a
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy web"
          git push origin gh-pages -f
          
